# Generated by Django 3.0.8 on 2020-07-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(db_index=True, max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60, null=True)),
                ('symbol', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
