# Generated by Django 3.0.8 on 2020-07-28 19:40

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0003_conversionrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='conversionrate',
            unique_together={('base', 'date')},
        ),
        migrations.CreateModel(
            name='ConversionRateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rates', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converion_rate_histroy_base', to='currency_converter.Currency')),
            ],
            options={
                'unique_together': {('base', 'date')},
            },
        ),
    ]
