# Generated by Django 3.0.8 on 2020-07-28 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
import wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency_converter', '0004_auto_20200728_1940'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('balance', models.DecimalField(decimal_places=10, default=0.0, max_digits=30)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_currency', to='currency_converter.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('preferred_currency', models.ForeignKey(default=wallet.models.default_currency, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_preferred_currency', to='currency_converter.Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('system_transfer_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('actual_transfer_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('system_transfer_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('actual_transfer_amount', models.DecimalField(decimal_places=10, max_digits=30)),
                ('transfer_units', models.DecimalField(decimal_places=10, max_digits=30)),
                ('type', models.CharField(choices=[('FUND_TRANSFER', 'Transfer'), ('SELF_TRANSFER', 'Self Transfer'), ('ADD_FUNDS', 'Add Money'), ('WITHDRAW_FUNDS', 'Withdraw Money')], default='FUND_TRANSFER', max_length=50)),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
                ('transaction_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('transaction_status', models.CharField(choices=[('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20)),
                ('from_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_from_balance', to='wallet.Balance')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_from_currency', to='currency_converter.Currency')),
                ('to_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_to_balance', to='wallet.Balance')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_to_currency', to='currency_converter.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_wallet', to='wallet.Wallet'),
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('balance', models.DecimalField(decimal_places=10, default=0.0, max_digits=30)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_history_currency', to='currency_converter.Currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_history_order', to='wallet.Order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_history_wallet', to='wallet.Wallet')),
            ],
            options={
                'unique_together': {('wallet', 'currency')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('wallet', 'currency')},
        ),
    ]
