# Generated by Django 3.0.8 on 2020-07-29 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200729_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='balancehistory',
            unique_together=set(),
        ),
    ]
