# Generated by Django 3.0.8 on 2020-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20200729_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_transfer_rate',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='system_transfer_rate',
            field=models.DecimalField(decimal_places=10, default=1.0, max_digits=20),
        ),
    ]
