# Generated by Django 3.0.8 on 2020-07-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20200729_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_status',
            new_name='status',
        ),
    ]
