# Generated by Django 3.0.8 on 2020-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20200729_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('FUND_TRANSFER', 'Fund Transfer'), ('SELF_FUND_TRANSFER', 'Self Fund Transfer'), ('ADD_FUNDS', 'Add Funds'), ('WITHDRAW_FUNDS', 'Withdraw Funds')], default='FUND_TRANSFER', max_length=50),
        ),
    ]
