# Generated by Django 3.0.8 on 2020-07-28 13:20

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200728_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rates', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
